### ISSUE TITLE
4 - Comparación de varios modelos de aprendizaje automático en función de una métrica de rendimiento

### ISSUE THREAD

**Issue by MartinO32** [MartinO32/PP1_grupo23#4]

**Comment by Daniela-vbd** [comment]
6. Modelos
6.1 División del dataframe en features y target
6.2 Implementación del modelo de clasificación
6.3 Importancia de las características
6.4 Rendimiento y mejores hiperparámetros para cada modelos
6.5 Conjuntos de entrenamiento y de prueba
6.6 Gráficos de distribución de cada variable
